# Generated by Django 3.0.4 on 2020-04-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryID', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('Quantity', models.CharField(max_length=100)),
                ('ShortDesc', models.CharField(max_length=100)),
                ('LongDesc', models.CharField(max_length=100)),
                ('stock', models.FloatField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
    ]
